version: "3"

set: ["u", "pipefail"]
shopt: ["globstar"]

includes:
  bazel: "taskfiles/bazel.yaml"
  cpp: "taskfiles/cpp.yaml"
  deps: "taskfiles/deps.yaml"
  go: "taskfiles/go.yaml"
  lint: "taskfiles/lint.yaml"

vars:
  G_BUILD_DIR: "{{.ROOT_DIR}}/build"

tasks:
  build:
    deps:
      - "bazel:build"
      - "go:build"

  clean:
    deps:
      - "bazel:clean"
      - "cpp:clean"
      - "go:clean"
    cmd: "rm -fr {{.G_BUILD_DIR}}"

  test:
    deps:
      - "bazel:test"
      - "go:test"

  init:
    internal: true
    silent: true
    run: "once"
    cmd: "mkdir -p '{{.G_BUILD_DIR}}'"
