// Code generated by "stringer -type=IRError"; DO NOT EDIT.

package ir

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-0]
	_ = x[DecodeError-1]
	_ = x[EOIR-2]
	_ = x[CorruptedIR-3]
	_ = x[CorruptedMetadata-4]
	_ = x[IncompleteIR-5]
	_ = x[UnsupportedVersion-6]
	_ = x[EncodeError-7]
}

const _IRError_name = "SuccessDecodeErrorEOIRCorruptedIRCorruptedMetadataIncompleteIRUnsupportedVersionEncodeError"

var _IRError_index = [...]uint8{0, 7, 18, 22, 33, 50, 62, 80, 91}

func (i IRError) String() string {
	if i < 0 || i >= IRError(len(_IRError_index)-1) {
		return "IRError(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IRError_name[_IRError_index[i]:_IRError_index[i+1]]
}
